title: iperf
description: iperf windows builds
show_downloads: true
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
relative_links:
  enabled: true
  collections: true
include:
  - README.md
github:
  zip_url: https://github.com/kdpuvvadi/iperf/releases/download/3.17.1/iperf-3.17.1.zip
  tar_url: https://github.com/kdpuvvadi/iperf/releases/download/3.17.1/iperf-3.17.1.tar.gz
